'------------------------------------------------------------------------------
' <auto-generated>
'
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>  _
Partial Friend NotInheritable Class ViewSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As ViewSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ViewSettings()),ViewSettings)
    
    Public Shared ReadOnly Property [Default]() As ViewSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property AppMaximized() As Boolean
        Get
            Return CType(Me("AppMaximized"),Boolean)
        End Get
        Set
            Me("AppMaximized") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")>  _
    Public Property AppBounds() As Global.System.Drawing.Rectangle
        Get
            Return CType(Me("AppBounds"),Global.System.Drawing.Rectangle)
        End Get
        Set
            Me("AppBounds") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property SelectedWindowName() As String
        Get
            Return CType(Me("SelectedWindowName"),String)
        End Get
        Set
            Me("SelectedWindowName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("60000")>  _
    Public Property AutoUpdateFrequency() As Integer
        Get
            Return CType(Me("AutoUpdateFrequency"),Integer)
        End Get
        Set
            Me("AutoUpdateFrequency") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property AutoUpdateEnabled() As Boolean
        Get
            Return CType(Me("AutoUpdateEnabled"),Boolean)
        End Get
        Set
            Me("AutoUpdateEnabled") = value
        End Set
    End Property
End Class
