'------------------------------------------------------------------------------
' <auto-generated>
'
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '''<summary>
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProcessLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorLogBackupImportFileFailed() As String
            Get
                Return ResourceManager.GetString("ErrorLogBackupImportFileFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorLogOutputFileNameIsInvalid() As String
            Get
                Return ResourceManager.GetString("ErrorLogOutputFileNameIsInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageFileAccessError() As String
            Get
                Return ResourceManager.GetString("ErrorMessageFileAccessError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ExistUnprocessedData() As String
            Get
                Return ResourceManager.GetString("ExistUnprocessedData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionAndLess() As String
            Get
                Return ResourceManager.GetString("FilterConditionAndLess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionAndMore() As String
            Get
                Return ResourceManager.GetString("FilterConditionAndMore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionBackwardMatch() As String
            Get
                Return ResourceManager.GetString("FilterConditionBackwardMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionEqual() As String
            Get
                Return ResourceManager.GetString("FilterConditionEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionExactMatch() As String
            Get
                Return ResourceManager.GetString("FilterConditionExactMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionForwardMatch() As String
            Get
                Return ResourceManager.GetString("FilterConditionForwardMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionFrom() As String
            Get
                Return ResourceManager.GetString("FilterConditionFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionInclude() As String
            Get
                Return ResourceManager.GetString("FilterConditionInclude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionLessThan() As String
            Get
                Return ResourceManager.GetString("FilterConditionLessThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionMoreThan() As String
            Get
                Return ResourceManager.GetString("FilterConditionMoreThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionNotEqual() As String
            Get
                Return ResourceManager.GetString("FilterConditionNotEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionNotInclude() As String
            Get
                Return ResourceManager.GetString("FilterConditionNotInclude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionNotMatch() As String
            Get
                Return ResourceManager.GetString("FilterConditionNotMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionPeriod() As String
            Get
                Return ResourceManager.GetString("FilterConditionPeriod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FilterConditionUntil() As String
            Get
                Return ResourceManager.GetString("FilterConditionUntil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FontName() As String
            Get
                Return ResourceManager.GetString("FontName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property HistoryColumnDisplayNameFormat() As String
            Get
                Return ResourceManager.GetString("HistoryColumnDisplayNameFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PrintPageFormat() As String
            Get
                Return ResourceManager.GetString("PrintPageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PrintSettingsError() As String
            Get
                Return ResourceManager.GetString("PrintSettingsError", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
