'------------------------------------------------------------------------------
' <auto-generated>
'
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '''<summary>
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UtilityLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorLogBackUpFailed() As String
            Get
                Return ResourceManager.GetString("ErrorLogBackUpFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorLogCaptureFailed() As String
            Get
                Return ResourceManager.GetString("ErrorLogCaptureFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorLogDeleteFileFailed() As String
            Get
                Return ResourceManager.GetString("ErrorLogDeleteFileFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorLogFormatError() As String
            Get
                Return ResourceManager.GetString("ErrorLogFormatError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageCreateErrorFile() As String
            Get
                Return ResourceManager.GetString("ErrorMessageCreateErrorFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageFileAccessError() As String
            Get
                Return ResourceManager.GetString("ErrorMessageFileAccessError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportAccessDenied() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportAccessDenied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportColumnExceedance() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportColumnExceedance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportConverted() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportConverted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportDuplication() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportDuplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportExceedByteLength() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportExceedByteLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportFailure() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportFileNotFound() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportFileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportFileOnNetwork() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportFileOnNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportOverflow() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportOverflow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageImportTruncated() As String
            Get
                Return ResourceManager.GetString("ErrorMessageImportTruncated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageOutputSettings() As String
            Get
                Return ResourceManager.GetString("ErrorMessageOutputSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PC_FilterOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PC_FilterOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PC_FilterOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PC_FilterOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
