'------------------------------------------------------------------------------
' <auto-generated>
'
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '''<summary>
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ViewLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ButtonAutoUpdateSetting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonAutoUpdateSetting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ClearColumnFailed() As String
            Get
                Return ResourceManager.GetString("ClearColumnFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ClearColumnSuccess() As String
            Get
                Return ResourceManager.GetString("ClearColumnSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ClearRowsFailed() As String
            Get
                Return ResourceManager.GetString("ClearRowsFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ClearRowsSuccess() As String
            Get
                Return ResourceManager.GetString("ClearRowsSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property Closing() As String
            Get
                Return ResourceManager.GetString("Closing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ConfirmationMessageClearButton() As String
            Get
                Return ResourceManager.GetString("ConfirmationMessageClearButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ConfirmationMessageDeleteAllData() As String
            Get
                Return ResourceManager.GetString("ConfirmationMessageDeleteAllData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ConfirmationMessageUpdateInventory() As String
            Get
                Return ResourceManager.GetString("ConfirmationMessageUpdateInventory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ConnectionError() As String
            Get
                Return ResourceManager.GetString("ConnectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property DestockingFailed() As String
            Get
                Return ResourceManager.GetString("DestockingFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property DestockingSuccess() As String
            Get
                Return ResourceManager.GetString("DestockingSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property DownAllow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownAllow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorInvalidTarget() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidTarget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageBackUpFailed() As String
            Get
                Return ResourceManager.GetString("ErrorMessageBackUpFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageDeleteFailed() As String
            Get
                Return ResourceManager.GetString("ErrorMessageDeleteFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageFailedCallTransferApp() As String
            Get
                Return ResourceManager.GetString("ErrorMessageFailedCallTransferApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageFailedCloseTransferApp() As String
            Get
                Return ResourceManager.GetString("ErrorMessageFailedCloseTransferApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageFailedStartTransferApp() As String
            Get
                Return ResourceManager.GetString("ErrorMessageFailedStartTransferApp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ErrorMessageUpdateViewFailed() As String
            Get
                Return ResourceManager.GetString("ErrorMessageUpdateViewFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FileOutputFailed() As String
            Get
                Return ResourceManager.GetString("FileOutputFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FileOutputSuccess() As String
            Get
                Return ResourceManager.GetString("FileOutputSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property FolderCreateFailed() As String
            Get
                Return ResourceManager.GetString("FolderCreateFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property MessageOutputCsv() As String
            Get
                Return ResourceManager.GetString("MessageOutputCsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PC_FilterOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PC_FilterOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PC_FilterOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PC_FilterOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PrintFailed() As String
            Get
                Return ResourceManager.GetString("PrintFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PrintNoData() As String
            Get
                Return ResourceManager.GetString("PrintNoData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PrintSettingsError() As String
            Get
                Return ResourceManager.GetString("PrintSettingsError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property PrintSuccess() As String
            Get
                Return ResourceManager.GetString("PrintSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ProgressGraphRestTextFormat() As String
            Get
                Return ResourceManager.GetString("ProgressGraphRestTextFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ResendAllRecord() As String
            Get
                Return ResourceManager.GetString("ResendAllRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ResendSelectRecord() As String
            Get
                Return ResourceManager.GetString("ResendSelectRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SearchStringOther() As String
            Get
                Return ResourceManager.GetString("SearchStringOther", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property UpAllow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UpAllow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property WarningCannotClearKeyColumn() As String
            Get
                Return ResourceManager.GetString("WarningCannotClearKeyColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property WarnInvaridPeriod() As String
            Get
                Return ResourceManager.GetString("WarnInvaridPeriod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property WriteDatabaseFailed() As String
            Get
                Return ResourceManager.GetString("WriteDatabaseFailed", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
