'------------------------------------------------------------------------------
' <auto-generated>
'
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '''<summary>
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Database.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property AddColumnSql() As String
            Get
                Return ResourceManager.GetString("AddColumnSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property AsSql() As String
            Get
                Return ResourceManager.GetString("AsSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property AttachSql() As String
            Get
                Return ResourceManager.GetString("AttachSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property AverageSql() As String
            Get
                Return ResourceManager.GetString("AverageSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property BeginTransactionSql() As String
            Get
                Return ResourceManager.GetString("BeginTransactionSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CaseSql() As String
            Get
                Return ResourceManager.GetString("CaseSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CastIntegerString() As String
            Get
                Return ResourceManager.GetString("CastIntegerString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CastString() As String
            Get
                Return ResourceManager.GetString("CastString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CastToRealSql() As String
            Get
                Return ResourceManager.GetString("CastToRealSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CommitTransactionSql() As String
            Get
                Return ResourceManager.GetString("CommitTransactionSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ConnectionString() As String
            Get
                Return ResourceManager.GetString("ConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CountAllSql() As String
            Get
                Return ResourceManager.GetString("CountAllSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CountSql() As String
            Get
                Return ResourceManager.GetString("CountSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CreateGroupSumTempTable() As String
            Get
                Return ResourceManager.GetString("CreateGroupSumTempTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CreateIndexSql() As String
            Get
                Return ResourceManager.GetString("CreateIndexSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CreateNewDataTempTable() As String
            Get
                Return ResourceManager.GetString("CreateNewDataTempTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property CreateTableSql() As String
            Get
                Return ResourceManager.GetString("CreateTableSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property DateTimeCalculationSql() As String
            Get
                Return ResourceManager.GetString("DateTimeCalculationSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property DateTimeSql() As String
            Get
                Return ResourceManager.GetString("DateTimeSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property DeleteColumnSql() As String
            Get
                Return ResourceManager.GetString("DeleteColumnSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property DeleteSql() As String
            Get
                Return ResourceManager.GetString("DeleteSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property DropTableIfExistSql() As String
            Get
                Return ResourceManager.GetString("DropTableIfExistSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property DropTableSql() As String
            Get
                Return ResourceManager.GetString("DropTableSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ExistsSql() As String
            Get
                Return ResourceManager.GetString("ExistsSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ExistTableSql() As String
            Get
                Return ResourceManager.GetString("ExistTableSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ExportCommand() As String
            Get
                Return ResourceManager.GetString("ExportCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property GetFieldsSql() As String
            Get
                Return ResourceManager.GetString("GetFieldsSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property GetTableSchemaSql() As String
            Get
                Return ResourceManager.GetString("GetTableSchemaSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ImportColumnExceedanceError() As String
            Get
                Return ResourceManager.GetString("ImportColumnExceedanceError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ImportCommand() As String
            Get
                Return ResourceManager.GetString("ImportCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ImportDuplicationError() As String
            Get
                Return ResourceManager.GetString("ImportDuplicationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property InsertSelectSql() As String
            Get
                Return ResourceManager.GetString("InsertSelectSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property InsertSql() As String
            Get
                Return ResourceManager.GetString("InsertSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property IsNullSql() As String
            Get
                Return ResourceManager.GetString("IsNullSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property LogElapsedTime() As String
            Get
                Return ResourceManager.GetString("LogElapsedTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property LogPlaceHolder() As String
            Get
                Return ResourceManager.GetString("LogPlaceHolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property LogRetransmissionCondition() As String
            Get
                Return ResourceManager.GetString("LogRetransmissionCondition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property MaxSql() As String
            Get
                Return ResourceManager.GetString("MaxSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property NotSql() As String
            Get
                Return ResourceManager.GetString("NotSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ReplaceSql() As String
            Get
                Return ResourceManager.GetString("ReplaceSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property ResultColumnName() As String
            Get
                Return ResourceManager.GetString("ResultColumnName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property RollbackTransactionSql() As String
            Get
                Return ResourceManager.GetString("RollbackTransactionSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property RoundString() As String
            Get
                Return ResourceManager.GetString("RoundString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SelectDistinctSql() As String
            Get
                Return ResourceManager.GetString("SelectDistinctSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SelectFilterTreeItem() As String
            Get
                Return ResourceManager.GetString("SelectFilterTreeItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SelectIndexSql() As String
            Get
                Return ResourceManager.GetString("SelectIndexSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SelectSql() As String
            Get
                Return ResourceManager.GetString("SelectSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SelectSqlForCalculationLabel() As String
            Get
                Return ResourceManager.GetString("SelectSqlForCalculationLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SelectSqlForLogUpdate() As String
            Get
                Return ResourceManager.GetString("SelectSqlForLogUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SelectTableAndViewSql() As String
            Get
                Return ResourceManager.GetString("SelectTableAndViewSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SelectTableSql() As String
            Get
                Return ResourceManager.GetString("SelectTableSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SelectViewSql() As String
            Get
                Return ResourceManager.GetString("SelectViewSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SetSqlForLogUpdateAssignment() As String
            Get
                Return ResourceManager.GetString("SetSqlForLogUpdateAssignment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SetSqlForLogUpdateCalculate() As String
            Get
                Return ResourceManager.GetString("SetSqlForLogUpdateCalculate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SQLite3ExitCommand() As String
            Get
                Return ResourceManager.GetString("SQLite3ExitCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SQLite3ImportCommand() As String
            Get
                Return ResourceManager.GetString("SQLite3ImportCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SQLite3SeparatorCommand() As String
            Get
                Return ResourceManager.GetString("SQLite3SeparatorCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property strftimeSql() As String
            Get
                Return ResourceManager.GetString("strftimeSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property SumSql() As String
            Get
                Return ResourceManager.GetString("SumSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property UpdateSql() As String
            Get
                Return ResourceManager.GetString("UpdateSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property UpdateSqlForUpdateInventory() As String
            Get
                Return ResourceManager.GetString("UpdateSqlForUpdateInventory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property UpdateSqlForUpdateInventoryNull() As String
            Get
                Return ResourceManager.GetString("UpdateSqlForUpdateInventoryNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property WalCommitCommand() As String
            Get
                Return ResourceManager.GetString("WalCommitCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend ReadOnly Property WhereSql() As String
            Get
                Return ResourceManager.GetString("WhereSql", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
