'------------------------------------------------------------------------------
' <auto-generated>
'
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '''<summary>
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SqlResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DatabaseLibrary.SqlResources", GetType(SqlResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property AddColumnSql() As String
            Get
                Return ResourceManager.GetString("AddColumnSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property AsSql() As String
            Get
                Return ResourceManager.GetString("AsSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property AttachSql() As String
            Get
                Return ResourceManager.GetString("AttachSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property AverageSql() As String
            Get
                Return ResourceManager.GetString("AverageSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property BeginTransactionSql() As String
            Get
                Return ResourceManager.GetString("BeginTransactionSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property CaseSql() As String
            Get
                Return ResourceManager.GetString("CaseSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property CastToRealSql() As String
            Get
                Return ResourceManager.GetString("CastToRealSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property CommitTransactionSql() As String
            Get
                Return ResourceManager.GetString("CommitTransactionSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property ConnectionString() As String
            Get
                Return ResourceManager.GetString("ConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property CountAllSql() As String
            Get
                Return ResourceManager.GetString("CountAllSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property CountSql() As String
            Get
                Return ResourceManager.GetString("CountSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property CreateGroupSumTempTable() As String
            Get
                Return ResourceManager.GetString("CreateGroupSumTempTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property CreateIndexSql() As String
            Get
                Return ResourceManager.GetString("CreateIndexSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property CreateNewDataTempTable() As String
            Get
                Return ResourceManager.GetString("CreateNewDataTempTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property CreateTableSql() As String
            Get
                Return ResourceManager.GetString("CreateTableSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property DateTimeCalculationSql() As String
            Get
                Return ResourceManager.GetString("DateTimeCalculationSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property DateTimeSql() As String
            Get
                Return ResourceManager.GetString("DateTimeSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property DeleteColumnSql() As String
            Get
                Return ResourceManager.GetString("DeleteColumnSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property DeleteSql() As String
            Get
                Return ResourceManager.GetString("DeleteSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property DropTableSql() As String
            Get
                Return ResourceManager.GetString("DropTableSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property ExistsSql() As String
            Get
                Return ResourceManager.GetString("ExistsSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property ExportCommand() As String
            Get
                Return ResourceManager.GetString("ExportCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property GetFieldsSql() As String
            Get
                Return ResourceManager.GetString("GetFieldsSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property GetTableSchemaSql() As String
            Get
                Return ResourceManager.GetString("GetTableSchemaSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property ImportColumnExceedanceError() As String
            Get
                Return ResourceManager.GetString("ImportColumnExceedanceError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property ImportCommand() As String
            Get
                Return ResourceManager.GetString("ImportCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property ImportDuplicationError() As String
            Get
                Return ResourceManager.GetString("ImportDuplicationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property InsertSelectSql() As String
            Get
                Return ResourceManager.GetString("InsertSelectSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property InsertSql() As String
            Get
                Return ResourceManager.GetString("InsertSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property IsNullSql() As String
            Get
                Return ResourceManager.GetString("IsNullSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property LogRetransmissionCondition() As String
            Get
                Return ResourceManager.GetString("LogRetransmissionCondition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property NotSql() As String
            Get
                Return ResourceManager.GetString("NotSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property ResultColumnName() As String
            Get
                Return ResourceManager.GetString("ResultColumnName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property RollbackTransactionSql() As String
            Get
                Return ResourceManager.GetString("RollbackTransactionSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SelectSql() As String
            Get
                Return ResourceManager.GetString("SelectSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SelectSqlForCalculationLabel() As String
            Get
                Return ResourceManager.GetString("SelectSqlForCalculationLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SelectSqlForLogUpdate() As String
            Get
                Return ResourceManager.GetString("SelectSqlForLogUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SelectTableAndViewSql() As String
            Get
                Return ResourceManager.GetString("SelectTableAndViewSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SelectTableSql() As String
            Get
                Return ResourceManager.GetString("SelectTableSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SelectViewSql() As String
            Get
                Return ResourceManager.GetString("SelectViewSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SetSqlForLogUpdate() As String
            Get
                Return ResourceManager.GetString("SetSqlForLogUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SQLite3ExitCommand() As String
            Get
                Return ResourceManager.GetString("SQLite3ExitCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SQLite3ImportCommand() As String
            Get
                Return ResourceManager.GetString("SQLite3ImportCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SQLite3SeparatorCommand() As String
            Get
                Return ResourceManager.GetString("SQLite3SeparatorCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property strftimeSql() As String
            Get
                Return ResourceManager.GetString("strftimeSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property SumSql() As String
            Get
                Return ResourceManager.GetString("SumSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property UpdateSql() As String
            Get
                Return ResourceManager.GetString("UpdateSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property UpdateSqlForUpdateInventoryEqual() As String
            Get
                Return ResourceManager.GetString("UpdateSqlForUpdateInventoryEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property UpdateSqlForUpdateInventoryNotEqual() As String
            Get
                Return ResourceManager.GetString("UpdateSqlForUpdateInventoryNotEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property UpdateSqlForUpdateInventoryNull() As String
            Get
                Return ResourceManager.GetString("UpdateSqlForUpdateInventoryNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property WalCommitCommand() As String
            Get
                Return ResourceManager.GetString("WalCommitCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''</summary>
        Friend Shared ReadOnly Property WhereSql() As String
            Get
                Return ResourceManager.GetString("WhereSql", resourceCulture)
            End Get
        End Property
    End Class
End Namespace

